### PR TITLE
fix: URL for Expo Go projects

### PR DESCRIPTION
**Pull request by sguha00**
### Linked issue

https://github.com/expo/expo-preview-action/issues/3

### CODE REVIEW

**Review by thebiltheory — APPROVED** [review]

**Comment by lukmccall** [comment]
Thanks for your contribution 💪 
Could you fix the CI error?

**Comment by cvburgess** [comment]
Hitting this error with our previews, anything I can do to speed this along?

**Comment by sguha00** [comment]
> Hitting this error with our previews, anything I can do to speed this along?
I fixed the diffs manually in the index.js file and the tests should now pass. Any idea why my local `yarn build` produces a different build/index.js?

**Comment by sguha00** [comment]
@lukmccall Can you approve the github actions?

**Comment by cvburgess** [comment]
For whats its worth I could not get Go or a custom development client's QR code to work.
I used the docs and am now manually crafting a working URL for a custom client - here's my comment:

```hbs
Successfully deployed to Expo! You can scan the QR code or [preview the PR here](https://expo.io/@seql/sonic-boom?release-channel=pr-${{ github.event.number }}).
<br><br>
<img src="https://qr.expo.dev/development-client?appScheme=exp%2Bsonic-boom&url=https://exp.host/@seql/sonic-boom/index.exp?release-channel=pr-${{ github.event.number }}&sdkVersion=42.0.0" height="256px" 
<br><br>
${{ steps.publish.outputs.EXPO_NEW_BUILD_IS_REQUIRED_MESSAGE }}
```

**Comment by lukmccall** [comment]
Hi @cvburgess, which version of the `expo-dev-client` are you using? It has to be at least `0.4.7`, due to a bug in that package. For more information check out https://github.com/expo/expo/issues/13711#issuecomment-894475486.

**Pull request merged**
